# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vrk < Formula
  desc "Unix tools for building reliable AI pipelines"
  homepage "https://vrk.sh"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vrksh/vrksh/releases/download/v0.1.0/vrk_0.1.0_darwin_amd64.tar.gz"
      sha256 "933989d7c725b430cc72e2b38321736ec1686643feb0b092369a15d121ecc91c"

      define_method(:install) do
        bin.install "vrk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vrksh/vrksh/releases/download/v0.1.0/vrk_0.1.0_darwin_arm64.tar.gz"
      sha256 "3f4bdff4366956fbe859cf6be8daf5f42dd5fb4663225c1ee602d0f1d8b3402f"

      define_method(:install) do
        bin.install "vrk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vrksh/vrksh/releases/download/v0.1.0/vrk_0.1.0_linux_amd64.tar.gz"
      sha256 "ab932dae2156a882a268a0216d349c5e8e7ac70960b02b77d99421978f37dcc8"
      define_method(:install) do
        bin.install "vrk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vrksh/vrksh/releases/download/v0.1.0/vrk_0.1.0_linux_arm64.tar.gz"
      sha256 "5cb351515a803761f96cbc85e8eed2ad18c2f26d68d180f85425cf8e8d118c1a"
      define_method(:install) do
        bin.install "vrk"
      end
    end
  end

  test do
    system "#{bin}/vrk", "--help"
  end
end
