# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vrk < Formula
  desc "Unix tools for building reliable AI pipelines"
  homepage "https://vrk.sh"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vrksh/vrksh/releases/download/v0.1.1/vrk_0.1.1_darwin_amd64.tar.gz"
      sha256 "9d491498938b04108daeeb398a34fe725ef96349ebeb74db0662b9a9a296221d"

      define_method(:install) do
        bin.install "vrk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vrksh/vrksh/releases/download/v0.1.1/vrk_0.1.1_darwin_arm64.tar.gz"
      sha256 "a1de3446aa9dd36612171f7910831b7ddbf76c01298a03dfe83eaebb3d122a75"

      define_method(:install) do
        bin.install "vrk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vrksh/vrksh/releases/download/v0.1.1/vrk_0.1.1_linux_amd64.tar.gz"
      sha256 "70bd1a3460cf943c8ae55a7156f803cd89788ffe8147e72deee71132d038c2fe"
      define_method(:install) do
        bin.install "vrk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vrksh/vrksh/releases/download/v0.1.1/vrk_0.1.1_linux_arm64.tar.gz"
      sha256 "a5ddc4617f51a9614648ef769d893c4c40859de91a4210631a23c6e5830c6b00"
      define_method(:install) do
        bin.install "vrk"
      end
    end
  end

  test do
    system "#{bin}/vrk", "--help"
  end
end
