# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vrk < Formula
  desc "Unix tools for building reliable AI pipelines"
  homepage "https://vrk.sh"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vrksh/vrksh/releases/download/v0.1.0/vrk_0.1.0_darwin_amd64.tar.gz"
      sha256 "9609f5f87f5556434c0ed04938c50e62c5ccdd71869833d5cac2d80e8df00e84"

      define_method(:install) do
        bin.install "vrk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vrksh/vrksh/releases/download/v0.1.0/vrk_0.1.0_darwin_arm64.tar.gz"
      sha256 "46fed35aab5726fe3736cc15e19c786abdfa425d2cdbb61eb71b84988b5bed30"

      define_method(:install) do
        bin.install "vrk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vrksh/vrksh/releases/download/v0.1.0/vrk_0.1.0_linux_amd64.tar.gz"
      sha256 "b9171116486f3faf509d79a20e0e311880b2f010a0bcb5e4439383cbea141dfa"
      define_method(:install) do
        bin.install "vrk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vrksh/vrksh/releases/download/v0.1.0/vrk_0.1.0_linux_arm64.tar.gz"
      sha256 "cafce3460c76fe54a63bdf03b23e9836f6f4f22cb8ad1fb2347b2ad9753cacdf"
      define_method(:install) do
        bin.install "vrk"
      end
    end
  end

  test do
    system "#{bin}/vrk", "--help"
  end
end
